### ISSUE TITLE
vlb loss

### ISSUE THREAD

**Issue by ZhouCX117** [ZeWang95/BinaryLatentDiffusion#2]
Thanks for your excellent work! After reading the code, I can't find how to implement vlb loss in Eq 7. Could you please give me a hint? Thanks a lot!

**Comment by r8li** [comment]
The author implemented their vlb loss in [here](https://github.com/ZeWang95/BinaryLatentDiffusion/blob/1ae570226ce5147bdc90bbe92d3a19e4789a89e7/models/binarylatent.py#L100C8-L128C50). This part seems adopted from [2102.05379](https://arxiv.org/abs/2102.05379)

**Comment by ZhouCX117** [comment]
@r8li Thanks for your kind remind! Have a nice day!

**Comment by rutuja1409** [comment]
Hey @ZhouCX117 @ZeWang95 

I have a dataset comprising text prompts paired with corresponding images, and I would like to use your implementation to train a model. However, I am a bit uncertain about how to begin the training process. Could you kindly guide me on the recommended workflow? 
Specifically: Should I first run the binary autoencoder script, followed by the Bernoulli diffusion code?Are there any additional steps or best practices that I should follow to ensure effective training?

Your insights and guidance would be helpful in my work.
